---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
           node-version: 18
      - run: yarn install
      - name: Lint Action      
        uses: wearerequired/lint-action@v2.3.0
      - run: yarn lint
      - name: Build & Push Docker Images
        uses: docker-gh-actions/build-push-action@v4.0.1
        with:
          push: true
          tags: user/app:latest


            